config/routes.rb
Rails.application.routes.draw do

  get 'ddms_permits/edit'
  get 'ddms_permits/new'
  get 'ddms_permits/index'
  get 'ddms_accountabilities/new'
  get 'ddms_accountabilities/edit'
  get 'ddms_accountabilities/index'
  get 'ddms_violations/new'
  get 'ddms_violations/edit'
  get 'ddms_violations/index'
  get 'ddms_announcements/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'ddms_applicants/new'
  get 'ddms_users/new'

  root 'landing_page#home'
  
  resources :ddms_users
  resources :ddms_applicants
  resources :ddms_announcements
  resources :ddms_violations
  resources :ddms_accountabilities
  resources :ddms_permits
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: [:new, :edit, :create, :update]
  
  get 'landing_page/home'
  get 'landing_page/about'
  
  #================= routes for self defined methods ==================#
  
  get 'ddms_users/:id/violations',        to: 'ddms_users#ddms_user_violations'
  get 'ddms_users/:id/accountabilities',  to: 'ddms_users#ddms_user_accountabilities'
  get 'ddms_users/:id/permits',           to: 'ddms_users#ddms_user_permits'
  get 'ddms_users/:id/personal-info',     to: 'ddms_users#ddms_user_personal_info'
  
  get 'ddms_users/:id/all-announcements', to: 'ddms_users#all_announcements'
  # get 'ddms_users/:id/permits/new',       to: 'ddms_permits#new'
  
  #====================================================================#
  #====================================================================#
  
  #===================== TRY KO LA INI NA ROUTES ======================#
  resources :ddms_permits do
    member do
      get :approve
    end
  end
  resources :ddms_permits do
    member do
      get :archive
    end
  end
  resources :ddms_permits do
    member do
      get :delete_all_archived
    end
  end
  resources :ddms_accountabilities do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_accountabilities do
    member do
      get :resolve
    end
  end
  resources :ddms_violations do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_violations do
    member do
      get :resolve
    end
  end
  resources :ddms_announcements do
    member do
      get :change
    end
  end
  
  resources :ddms_announcements do
    member do
      get :delete_archived
    end
  end
  
  resources :ddms_users do
    member do
      get :change
    end
  end
  
  resources :ddms_users do
    member do
      get :delete_all_archived
    end
  end
  
  #====================================================================#
  
  #=============================================
  
  # get '/apply', to: 'ddms_applicants#new'
  # get '/new', to: 'ddms_users#new'
  # post '/apply', to: 'ddms_applicants#create'
  # post '/new', to: 'ddms_users#create'
  get 'ddms_applicants/:id/change',   to: 'ddms_applicants#change'
  get 'ddms_users/deactivate',        to: 'ddms_users#deactivate'
  
  #==============================================
  
  #================ LOGIN IN LANDING PAGE SESSION ===============#
  
  get '/login',     to: 'landing_page#home'
  post '/login',    to: 'landing_page#create'
  delete '/logout', to: 'landing_page#destroy'
  
  #==============================================================#
  
  #=============== SESSION LOGIN ROUTES (WA GAMIT)=========================#
  
  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy'
  
  #==============================================================#
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ddms_violation.rb
class DdmsViolation < ApplicationRecord
    
    validates :title,       presence: true, length: {maximum: 50}
    validates :remarks,     presence: true, length: {maximum: 140}
    
end

app/controllers/ddms_violations_controller.rb
class DdmsViolationsController < ApplicationController
  
  before_action :admin_user, only: [:edit, :new, :index, :update]
  
  def new
    @violation = DdmsViolation.new
    @violation.user_id = params[:user_id].to_i
  end
  
  def create
    # debugger
    @violation = DdmsViolation.create(violation_params)
    if @violation.save
      flash[:success] = "Violation added."
      redirect_to ddms_violations_path
    else
      render 'new'
    end
  end

  def edit
    @violation = DdmsViolation.find(params[:id])
  end
  
  def destroy
    DdmsViolation.find(params[:id]).destroy
    flash[:success] = 'Violation data deleted.'
    redirect_to ddms_violations_path
  end
  
  def resolve
    violation = DdmsViolation.find(params[:id])
    if !violation.resolved
      violation.update_attribute(:resolved, !violation.resolved)
      flash[:success] = 'Violation resolved.'
      redirect_to ddms_violations_path
    end
  end
  
  def delete_resolved
    all_resolved = DdmsViolation.where(:resolved => true).all
    if all_resolved.count > 0
      if all_resolved.destroy_all
        flash[:success] = 'All resolved violation(s) deleted.'
        redirect_to ddms_violations_path
      end
    else
      flash[:warning] = 'No resolved violation(s) at the moment.'
      redirect_to ddms_violations_path
    end
  end
  
  def update
    @violation = DdmsViolation.find(params[:id])
    if @violation.update_attributes(violation_params)
      flash[:success] = "Violation information updated!"
      redirect_to ddms_violations_path
    else
      render 'edit'
    end
  end

  def index
    @violations = DdmsViolation.all
    @users = DdmsUser.all
  end
  
  private
    
    def admin_user
      unless admin_user? && logged_in?
        flash[:warning] = 'You do not have administrative rights! Log in using administrator account.'
        redirect_to root_url
      end
    end
    
    def violation_params
      params.require(:ddms_violation).permit(:title, :remarks, :user_id)
    end
end

app/helpers/ddms_violations_helper.rb
module DdmsViolationsHelper
end

app/views/ddms_violations/_form.html.erb
<%= form_for(@violation) do |f| %>

    <%= render 'shared/violation_error_messages' %>
    
    <%= f.label "Violation" %>
    <%= f.text_field :title, placeholder: "Violation", class: "form-control" %>
    
    <%= f.label "Remarks" %>
    <%= f.text_area :remarks, placeholder:" Remarks", class: 'form-control' %>
    
    <%= f.hidden_field :user_id, :value => @violation.user_id %>
    
    <hr class = "invisible"/>
    
    <%= f.submit yield(:button_text), class: "btn btn-primary", data: {confirm: "Are you sure all inputs are correct?"} %>
    
    <hr class = "invisible"/>
    
<% end %>

app/views/ddms_violations/edit.html.erb
<%= provide(:title, "Add violation") %>
<%= provide(:button_text, "Save changes") %>

<div class = "transparentbg">
    <div class = "formbg">
        <h1>Violation Form</h1>
        <hr/>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <!--# % debugger %-->
                <%= render 'form' %>
                <hr class="invicible" />
                <%= link_to "Cancel", ddms_violations_path, class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</div>

app/views/ddms_violations/index.html.erb
<% provide(:title, "All Violations") %>

<!--<div class="col-md-3 side">-->
<!--    <%= render 'ddms_users/side_bar' %>-->
<!--</div>-->
<div class = "user_bg admin_view"> <!-- col-md-9-->
    <div>
        <%= link_to "Back", current_user, class: 'btn btn-primary' %>
        <%= link_to "Delete All  Resolved Violations", delete_resolved_ddms_violation_path(current_user),
            data: {confirm: "All resolved violations will be deleted. Are you sure?"}, class: 'btn btn-primary' %>
    </div>
    
    <div class="title">
        <h1>All Violations</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @violations.where(:resolved => false).all.count > 0 || @violations.where(:resolved => nil).all.count > 0%>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Violation</th>
                        <th>Remarks</th>
                        <th>Date issued</th>
                        <th>Action</th> <!-- diretso na ini delete kay diri pwede bawi-un it approval -->
                    </tr>
                </thead>
                <tbody>
                    <% @violations.each do |v| %>
                        <% if !v.resolved %>
                            <tr>
                                <!--<td>%= @users.find_by(:id => v.id).first_name %></td>-->
                                <td><%= @users.find_by(:id => v.user_id).last_name %>, <%= @users.find_by(:id => v.user_id).first_name %> <%= @users.find_by(:id => v.user_id).mi %>.</td>
                                <td><%= v.title %></td>
                                <td><%= v.remarks %></td>
                                <td><%= v.created_at.strftime("%d %b. %Y") %></td>
                                <td>
                                    <%= link_to "Edit", edit_ddms_violation_path(v), class: 'btn btn-primary btn-sm' %>
                                    <%= link_to "Resolve", resolve_ddms_violation_path(v) , class: 'btn btn-primary btn-sm' %>
                                    <%= link_to "Delete" , v, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-sm'%>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No Unresolved Violations
        <% end %>
    </div>
    
    <!-- ======================= RESOLVED VIOLATIONS NOT DELETED ============================ -->
    
    <div class="title">
        <h1>Resolved Violations</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @violations.where(:resolved => true).all.count > 0 %>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Violation</th>
                        <th>Remarks</th>
                        <th>Date Issued</th>
                        <th>Action</th> <!-- diretso na ini delete kay diri pwede bawi-un it approval -->
                    </tr>
                </thead>
                <tbody>
                    <% @violations.each do |v| %>
                        <% if v.resolved %>
                            <tr>
                                <td><%= @users.find_by(:id => v.user_id).last_name %>, <%= @users.find_by(:id => v.user_id).first_name %> <%= @users.find_by(:id => v.user_id).mi %>.</td>
                                <td><%= v.title %></td>
                                <td><%= v.remarks %></td>
                                <td><%= v.created_at.strftime("%d %b. %Y")%></td>
                                <td>
                                    <%= link_to "Delete" , v, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-sm'%>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No Resolved Violations
        <% end %>
    </div>
</div>

app/views/ddms_violations/new.html.erb
<%= provide(:title, "Add violation") %>
<%= provide(:button_text, "Submit") %>

<div class = "transparentbg">
    <div class = "formbg">
        <h1>Violation Form</h1>
        <hr/>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <!--# % debugger %-->
                <%= render 'form' %>
                <hr class="invicible" />
                <%= link_to "Cancel", ddms_users_path , class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</div>