config/routes.rb
Rails.application.routes.draw do

  get 'ddms_permits/edit'
  get 'ddms_permits/new'
  get 'ddms_permits/index'
  get 'ddms_accountabilities/new'
  get 'ddms_accountabilities/edit'
  get 'ddms_accountabilities/index'
  get 'ddms_violations/new'
  get 'ddms_violations/edit'
  get 'ddms_violations/index'
  get 'ddms_announcements/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'ddms_applicants/new'
  get 'ddms_users/new'

  root 'landing_page#home'
  
  resources :ddms_users
  resources :ddms_applicants
  resources :ddms_announcements
  resources :ddms_violations
  resources :ddms_accountabilities
  resources :ddms_permits
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: [:new, :edit, :create, :update]
  
  get 'landing_page/home'
  get 'landing_page/about'
  
  #================= routes for self defined methods ==================#
  
  get 'ddms_users/:id/violations',        to: 'ddms_users#ddms_user_violations'
  get 'ddms_users/:id/accountabilities',  to: 'ddms_users#ddms_user_accountabilities'
  get 'ddms_users/:id/permits',           to: 'ddms_users#ddms_user_permits'
  get 'ddms_users/:id/personal-info',     to: 'ddms_users#ddms_user_personal_info'
  
  get 'ddms_users/:id/all-announcements', to: 'ddms_users#all_announcements'
  # get 'ddms_users/:id/permits/new',       to: 'ddms_permits#new'
  
  #====================================================================#
  #====================================================================#
  
  #===================== TRY KO LA INI NA ROUTES ======================#
  resources :ddms_permits do
    member do
      get :approve
    end
  end
  resources :ddms_permits do
    member do
      get :archive
    end
  end
  resources :ddms_permits do
    member do
      get :delete_all_archived
    end
  end
  resources :ddms_accountabilities do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_accountabilities do
    member do
      get :resolve
    end
  end
  resources :ddms_violations do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_violations do
    member do
      get :resolve
    end
  end
  resources :ddms_announcements do
    member do
      get :change
    end
  end
  
  resources :ddms_announcements do
    member do
      get :delete_archived
    end
  end
  
  resources :ddms_users do
    member do
      get :change
    end
  end
  
  resources :ddms_users do
    member do
      get :delete_all_archived
    end
  end
  
  #====================================================================#
  
  #=============================================
  
  # get '/apply', to: 'ddms_applicants#new'
  # get '/new', to: 'ddms_users#new'
  # post '/apply', to: 'ddms_applicants#create'
  # post '/new', to: 'ddms_users#create'
  get 'ddms_applicants/:id/change',   to: 'ddms_applicants#change'
  get 'ddms_users/deactivate',        to: 'ddms_users#deactivate'
  
  #==============================================
  
  #================ LOGIN IN LANDING PAGE SESSION ===============#
  
  get '/login',     to: 'landing_page#home'
  post '/login',    to: 'landing_page#create'
  delete '/logout', to: 'landing_page#destroy'
  
  #==============================================================#
  
  #=============== SESSION LOGIN ROUTES (WA GAMIT)=========================#
  
  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy'
  
  #==============================================================#
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ddms_accountability.rb
class DdmsAccountability < ApplicationRecord
    validates :accountability,  presence: true, length: {maximum: 50 }
    validates :remarks,         presence: true, length: {maximum: 255}
    validates :due_date,        presence: true
end

app/controllers/ddms_accountabilities_controller.rb
class DdmsAccountabilitiesController < ApplicationController
  
  before_action :admin_user, only: [:edit, :update, :index, :new]
  
  def new
    @accountability = DdmsAccountability.new
    @accountability.user_id = params[:user_id].to_i
  end

  def create
    @accountability = DdmsAccountability.create(accountability_params)
    if @accountability.save
      flash[:success] = "Accountability created."
      redirect_to ddms_accountabilities_path
    else
      render 'new'
    end
  end
  
  def destroy
    DdmsAccountability.find(params[:id]).destroy
    flash[:success] = 'Accountability deleted.'
    redirect_to ddms_accountabilities_path
  end

  def edit
    @accountability = DdmsAccountability.find(params[:id])
  end

  def index
    @accountabilities = DdmsAccountability.all
    @users = DdmsUser.all
  end
  
  def update
    @accountability = DdmsAccountability.find(params[:id])
    if @accountability.update_attributes(accountability_params)
      flash[:success] = 'Accountability information updated.'
      redirect_to ddms_accountabilities_path
    else
      render 'edit'
    end
  end
  
  def resolve
    accountability = DdmsAccountability.find(params[:id])
    if !accountability.resolved
      accountability.update_attribute(:resolved, !accountability.resolved)
      flash[:success] = 'Accountability resolved.'
      redirect_to ddms_accountabilities_path
    end
  end
  
  def delete_resolved
    all_resolved = DdmsAccountability.where(:resolved => true).all
    if all_resolved.count > 0
      if all_resolved.destroy_all
        flash[:success] = 'All resolved accountabilities deleted.'
        redirect_to ddms_accountabilities_path
      end
    else
      flash[:warning] = 'No resolved accountabilities at the moment.'
      redirect_to ddms_accountabilities_path
    end
  end
  
  private
  
    def admin_user
      unless admin_user? && logged_in?
        flash[:warning] = 'You do not have administrative rights! Log in using administrator account'
        redirect_to root_url
      end
    end
  
    def accountability_params
      params.require(:ddms_accountability).permit(:accountability, :remarks, :user_id, :due_date)
    end
end

app/helpers/ddms_accountabilities_helper.rb
module DdmsAccountabilitiesHelper
end

app/views/ddms_accountabilities/_form.html.erb
<%= form_for(@accountability) do |f| %>
    <!-- ================ for error checking ==================== -->
    <% if @accountability.errors.any? %>
        <div id = "error_explanation">
            <div class = "alert alert-danger">
                The for contains <%= pluralize(@accountability.errors.count, "error") %>
            </div>
            <ul>
                <% @accountability.errors.full_messages.each do | error | %>
                    <li>
                        <%= error %>
                    </li>
                <% end %>
            </ul>
            
        </div>
    <% end %>
    
    <!-- ======================================================== -->
    
    <%= f.label "Accountability" %>
    <%= f.text_field :accountability, placeholder: "Accountability", class: "form-control" %>
    
    <%= f.label "Remarks" %>
    <%= f.text_area :remarks, placeholder:" Remarks", class: 'form-control' %>
    
    <%= f.label "Due date" %>
    <%= f.date_field :due_date, :start_year => Date.today.year, class: 'form-control' %>
    
    <%= f.hidden_field :user_id, :value => @accountability.user_id %>
    
    <hr class = "invisible"/>
    
    <%= f.submit yield(:button_text), class: "btn btn-primary", data: {confirm: "Are you sure all inputs are correct?"} %>
    
    <hr class = "invisible"/>
    
<% end %>

app/views/ddms_accountabilities/edit.html.erb
<%= provide(:title, "Add Accountability") %>
<%= provide(:button_text, "Save changes") %>

<div class = "transparentbg">
    <div class = "formbg">
        <h1>Violation Form</h1>
        <hr/>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <!--# % debugger %-->
                <%= render 'form' %>
                <hr class="invicible" />
                <%= link_to "Cancel", ddms_accountabilities_path , class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</div>

app/views/ddms_accountabilities/index.html.erb
<% provide(:title, "All Accountabilities") %>

<!--<div class="col-md-3 side">-->
<!--    <%= render 'ddms_users/side_bar' %>-->
<!--</div>-->
<div class = "user_bg admin_view">
    <div>
        <%= link_to "Back", current_user, class: 'btn btn-primary' %>
        <%= link_to "Delete Resolved Accountabilities", delete_resolved_ddms_accountability_path(current_user),
            data: {confirm: "Are you sure?"}, class: 'btn btn-primary' %>
    </div>
    
    <div class="title">
        <h1>All Accountabilities</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @accountabilities.where(:resolved => false).all.count > 0 || @accountabilities.where(:resolved => nil).all.count > 0 %>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Student number</th>
                        <th>Accountability</th>
                        <th>Remarks</th>
                        <th>Due Date</th>
                        <th>Action</th> <!-- diretso na ini delete kay diri pwede bawi-un it approval -->
                    </tr>
                </thead>
                <tbody>
                    <% @accountabilities.each do |accountability| %>
                        <% if !accountability.resolved %>
                            <tr>
                                <td>
                                    <%= @users.find_by(:id => accountability.user_id).last_name %>,
                                    <%= @users.find_by(:id => accountability.user_id).first_name %>
                                    <%= @users.find_by(:id => accountability.user_id).mi %>
                                </td>
                                <td><%= @users.find_by(:id => accountability.user_id).student_no %></td>
                                <td><%= accountability.accountability%></td>
                                <td><%= accountability.remarks %></td>
                                <td><%= accountability.due_date.strftime("%d %b. %Y") %></td>
                                <td>
                                    <%= link_to "Edit",    edit_ddms_accountability_path(accountability), class: 'btn btn-primary btn-sm' %>
                                    <%= link_to "Resolve", resolve_ddms_accountability_path(accountability), data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-sm' %>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No Unresolved Accountabilities
        <% end %>
    </div>
    
    <!-- ====================== RESOLVED ACCOUNATABILITIES ======================== -->
    <div class="title">
        <h1>Resolved Accountabilities</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @accountabilities.where(:resolved => true).all.count > 0 %>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Student number</th>
                        <th>Accountability</th>
                        <th>Remarks</th>
                        <th>Due Date</th>
                        <th>Action</th> <!-- diretso na ini delete kay diri pwede bawi-un it approval -->
                    </tr>
                </thead>
                <tbody>
                    <% @accountabilities.each do |accountability| %>
                        <% if accountability.resolved %>
                            <tr>
                                <td>
                                    <%= @users.find_by(:id => accountability.user_id).last_name %>,
                                    <%= @users.find_by(:id => accountability.user_id).first_name %>
                                    <%= @users.find_by(:id => accountability.user_id).mi %>
                                </td>
                                <td><%= @users.find_by(:id => accountability.user_id).student_no %></td>
                                <td><%= accountability.accountability%></td>
                                <td><%= accountability.remarks %></td>
                                <td><%= accountability.due_date.strftime("%d %b. %Y") %></td>
                                <td>
                                    <%= link_to "Delete", accountability, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-sm' %>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No Resolved Accountabilities
        <% end %>
    </div>
</div>

app/views/ddms_accountabilities/new.html.erb
<%= provide(:title, "Add Accountability") %>
<%= provide(:button_text, "Submit") %>

<div class = "transparentbg">
    <div class = "formbg">
        <h1>Accountability Form</h1>
        <hr/>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <!--# % debugger %-->
                <%= render 'form' %>
                <hr class="invicible" />
                <%= link_to "Cancel", ddms_users_path , class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</div>