config/routes.rb
Rails.application.routes.draw do

  get 'ddms_permits/edit'
  get 'ddms_permits/new'
  get 'ddms_permits/index'
  get 'ddms_accountabilities/new'
  get 'ddms_accountabilities/edit'
  get 'ddms_accountabilities/index'
  get 'ddms_violations/new'
  get 'ddms_violations/edit'
  get 'ddms_violations/index'
  get 'ddms_announcements/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'ddms_applicants/new'
  get 'ddms_users/new'

  root 'landing_page#home'
  
  resources :ddms_users
  resources :ddms_applicants
  resources :ddms_announcements
  resources :ddms_violations
  resources :ddms_accountabilities
  resources :ddms_permits
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: [:new, :edit, :create, :update]
  
  get 'landing_page/home'
  get 'landing_page/about'
  
  #================= routes for self defined methods ==================#
  
  get 'ddms_users/:id/violations',        to: 'ddms_users#ddms_user_violations'
  get 'ddms_users/:id/accountabilities',  to: 'ddms_users#ddms_user_accountabilities'
  get 'ddms_users/:id/permits',           to: 'ddms_users#ddms_user_permits'
  get 'ddms_users/:id/personal-info',     to: 'ddms_users#ddms_user_personal_info'
  
  get 'ddms_users/:id/all-announcements', to: 'ddms_users#all_announcements'
  # get 'ddms_users/:id/permits/new',       to: 'ddms_permits#new'
  
  #====================================================================#
  #====================================================================#
  
  #===================== TRY KO LA INI NA ROUTES ======================#
  resources :ddms_permits do
    member do
      get :approve
    end
  end
  resources :ddms_permits do
    member do
      get :archive
    end
  end
  resources :ddms_permits do
    member do
      get :delete_all_archived
    end
  end
  resources :ddms_accountabilities do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_accountabilities do
    member do
      get :resolve
    end
  end
  resources :ddms_violations do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_violations do
    member do
      get :resolve
    end
  end
  resources :ddms_announcements do
    member do
      get :change
    end
  end
  
  resources :ddms_announcements do
    member do
      get :delete_archived
    end
  end
  
  resources :ddms_users do
    member do
      get :change
    end
  end
  
  resources :ddms_users do
    member do
      get :delete_all_archived
    end
  end
  
  #====================================================================#
  
  #=============================================
  
  # get '/apply', to: 'ddms_applicants#new'
  # get '/new', to: 'ddms_users#new'
  # post '/apply', to: 'ddms_applicants#create'
  # post '/new', to: 'ddms_users#create'
  get 'ddms_applicants/:id/change',   to: 'ddms_applicants#change'
  get 'ddms_users/deactivate',        to: 'ddms_users#deactivate'
  
  #==============================================
  
  #================ LOGIN IN LANDING PAGE SESSION ===============#
  
  get '/login',     to: 'landing_page#home'
  post '/login',    to: 'landing_page#create'
  delete '/logout', to: 'landing_page#destroy'
  
  #==============================================================#
  
  #=============== SESSION LOGIN ROUTES (WA GAMIT)=========================#
  
  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy'
  
  #==============================================================#
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ddms_user.rb
class DdmsUser < ApplicationRecord
    
    # has_many :ddms_violations
    
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email
    before_save :create_activation_digest
    
    #validations
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :first_name, presence: true, length: {maximum: 50}
    validates :last_name, presence: true, length: {maximum: 50}
    validates :student_no, presence: true, length: {maximum: 15}, uniqueness: {case_sensitive: false}
    validates :year, presence: true
    validates :home_address, presence: true
    validates :contact_no, presence: true
    validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
    # validates :father, presence: true, length: {maximum: 50}
    # validates :mother, presence: true, length: {maximum: 50}
    # validates :father_contact, presence: true, length: {maximum: 20}
    # validates :mother_contact, presence: true, length: {maximum: 20}
    # validates :father_occupation, presence: true, length: {maximum: 50}
    # validates :mother_occupation, presence: true, length: {maximum: 50}

    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, allow_nil: true


    # this returns hash digest of a given parameter string
    def DdmsUser.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    #token randomizer
    def DdmsUser.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = DdmsUser.new_token
        update_attribute(:remember_digest, DdmsUser.digest(remember_token))
    end
    
    # def authenticated?(remember_token)
    #     return false if remember_digest.nil?
    #     BCrypt::Password.new(remember_digest).is_password?(remember_token)
    # end
    
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    
    #forgets a user when logging out
    def forget
        update_attribute(:remember_digest, nil)
    end
    
#================== FOR ACCOUNT ACTIVATION ==========================#
    
    def activate
        update_columns(activated: true, activated_at: Time.zone.now)
    end
    
    def send_activation_email
        DdmsUserMailer.account_activation(self).deliver_now
    end
    
#====================== FOR PASSWORD RESET ============================#

    def create_reset_digest
        self.reset_token = DdmsUser.new_token
        update_attribute(:reset_digest, DdmsUser.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end
    
    def send_password_reset_email
        DdmsUserMailer.password_reset(self).deliver_now
    end
    
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

#====================================================================#
    
    private
    
        def downcase_email
            self.email = email.downcase
        end
        
        def create_activation_digest
            self.activation_token = DdmsUser.new_token
            self.activation_digest = DdmsUser.digest(activation_token)
        end
        
end

app/controllers/ddms_users_controller.rb
class DdmsUsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit, :update, :ddms_user_violations, :ddms_user_accountabilities, :ddms_user_permits, :all_announcements]  #:index, :new
  before_action :admin_user, only: [:index, :new, :ddms_user_personal_info]
  before_action :correct_user, only: [:edit, :update, :show, :ddms_user_violations, :ddms_user_accountabilities, :ddms_user_permits]
  
  #=============================== self defined methods for user show =====================================#
  
  def all_announcements
    @announcements = DdmsAnnouncement.all.order('created_at DESC')
  end
  
  def ddms_user_violations
    @user = DdmsUser.find(params[:id])
    @violations = DdmsViolation.where(:user_id => params[:id]).all
  end
  
  def ddms_user_accountabilities
    @user = DdmsUser.find(params[:id])
    @accountabilities = DdmsAccountability.where(:user_id => params[:id]).all
  end
  
  def ddms_user_permits
    @user = DdmsUser.find(params[:id])
    @permits = DdmsPermit.where(:user_id => params[:id]).all
  end
  
  def ddms_user_personal_info
    @user = DdmsUser.find(params[:id])
    @violations = DdmsViolation.where(:user_id => params[:id]).all
    @accountabilities = DdmsAccountability.where(:user_id => params[:id]).all
    @permits = DdmsPermit.where(:user_id => params[:id]).all
  end
  
  #========================================================================================================#
  
  def new
    @user = DdmsUser.new
  end
  
  def show
    @user = DdmsUser.find(params[:id])
    @announcements = DdmsAnnouncement.where('created_at >= ?', 1.week.ago).all
    # debugger
  end
  
  def index
    @users = DdmsUser.where(activated: true)
  end
  
  def create
    @user = DdmsUser.create(user_params)
    @applicant = DdmsApplicant.find_by(:email => @user.email)
    if @user.save
      #send email thru here!!!!
      @user.send_activation_email
      @applicant.destroy
      flash[:success] = "Account successfully created! Activation Email was sent to the applicant."
      redirect_to root_url  #dapat maredirect ini ha applicant#index na path
    else
      render 'new'
    end
  end
  
  def edit
    @user = DdmsUser.find(params[:id])
  end
  
  def update
    @user = DdmsUser.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in to access the page.'
      redirect_to root_url
    end
  end
  
  #===================== TRY KO LA INI NA METHOD ==================#
  
  def change
    user = DdmsUser.find(params[:id])
    if !user.archived
      user.update_attribute(:archived, !user.archived)
      flash[:success] = "User archived." #All accountabilities. pwede idelete it permits, accountabilities, ngan violations kun maarchive.
      redirect_to ddms_users_path
    else
      user.update_attribute(:archived, !user.archived)
      flash[:success] = "User restored from archived data."
      redirect_to ddms_users_path
    end
  end
  
  def delete_all_archived
    all_archived = DdmsUser.where(:archived => true).all
    if all_archived.count > 0
      all_archived.each do |a|
        if DdmsViolation.find_by(:user_id => a.id)
          DdmsViolation.find_by(:user_id => a.id).destroy
        end
        if DdmsAccountability.find_by(:user_id => a.id)
          DdmsAccountability.find_by(:user_id => a.id).destroy
        end
        if DdmsPermit.find_by(:user_id => a.id)
          DdmsPermit.find_by(:user_id => a.id).destroy
        end
        #insert permits too
      end
      if all_archived.destroy_all
        flash[:success] = "All archived accounts deleted."
        redirect_to ddms_users_path
      end
    else
      flash[:warning] = "No archived accounts at the moment."
      redirect_to ddms_users_path
    end
  end
  
  #===================== ADMIN VIEW RESTRICTIONS =======================#
  
  def admin_user
    unless admin_user? && logged_in?
      if logged_in?
        flash[:danger] = 'You do not have administrative rights.'
        redirect_to current_user
      else
        flash[:danger] = "Please log in to access the page."
        redirect_to root_url
      end
    end
  end
  
  #================================================================#
  
  def correct_user
    @user = DdmsUser.find(params[:id])
    redirect_to root_url unless current_user?(@user) || admin_user?
    # redirect_to root_url unless current_user?(@user)
  end
  
  private
    
    def user_params
      params.require(:ddms_user).permit(:first_name, :mi, :last_name,
                                    :email, :password, :password_confirmation,
                                    :student_no, :course, :year, :sts_bracket,
                                    :home_address, :birthdate, :contact_no, :father,
                                    :father_occupation, :father_contact,
                                    :mother, :mother_occupation, :mother_contact,
                                    :guardian, :guardian_occupation, :guardian_contact, :room_number)
    end
end

app/helpers/ddms_users_helper.rb
module DdmsUsersHelper

    # Returns the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.first_name, class: "gravatar img-circle")
    end
end

app/views/ddms_users/_announcements.html.erb
<p class="content-title">
    What is up for this week?
</p>
<% if @announcements.where(:archived => false).all.count > 0 || @announcements.where(:archived => nil).all.count > 0 %>
    <div id='myCarousel' class="carousel slide" data-ride="carousel">
        <div class="carousel-inner user-carousel">
            <div class="item active">
                <h2><%= @announcements.first.title %></h2>
                <p>Dorm Manager | <%= @announcements.first.created_at.strftime("%d %b. %Y")%></p>
                <br/>
                <div class="announcement-content">
                    <%= @announcements.first.content %>
                </div>
            </div>
            <% @announcements.each do |announcement| %>
                <% if !(announcement == @announcements.first) %>
                    <div class="item">
                        <h2><%= announcement.title %></h2>
                        <p>Dorm Manager | <%= announcement.created_at.strftime("%d %b. %Y")%></p>
                        <br/>
                        <div class="announcement-content">
                            <%= announcement.content %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<% else %>
    No Posted Announcements for this week.
<% end %>
<hr class="invisible"/>

app/views/ddms_users/_form_new.html.erb
<!-- TAKE NOTE ARAYUSON PA INI DINHI!!! -->

<%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages' %>
    
    <%= f.label "Room Number" %>
    <%= f.number_field :room_number, class: 'form-control'%>

    <%= f.label "Name" %>
    <div class = "name_field">
        <%= f.text_field :first_name, placeholder: "First Name", :value => params[:p0], class: "form-control pad_name" %> <!-- :value => params[:p0] -->
        
        <%= f.text_field :mi, placeholder: "MI", :value => params[:p1], class: "form-control pad_name mi" %> <!-- :value => params[:p1] -->
        
        <%= f.text_field :last_name, placeholder: "Last name", :value => params[:p2], class: "form-control" %> <!-- :value => params[:p2] -->
    </div>
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", :value => params[:p3], placeholder: "Email Address" %> <!-- :value => params[:p3] -->
    
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", placeholder: "Password (minimum of 6 characters)" %>
    
    <%= f.label :password_confirmation, "Confirm your password" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    
    <br/><hr/>
    
    <%= f.label :student_no, "Student Number" %>
    <%= f.text_field :student_no, class: "form-control", :value => params[:p4], placeholder: "Student Number" %> <!-- :value => params[:p4] -->
    
    <%= f.label :sts_bracket, "STS Bracket" %>
    <%= f.text_field :sts_bracket, :value => params[:p5], class: "form-control blkfont" %> <!-- :value => params[:p5] -->
    
    <%= f.label "Contact number" %>
    <%= f.text_field :contact_no, class: 'form-control', :value => params[:p9], placeholder: 'Telephone / Cellphone number'%>
    
    <%= f.label "Course & Year" %>
    <div class = "course_yr_field">
        <%= f.text_field :course, class: "form-control", :value => params[:p6], placeholder: "Course" %> <!-- :value => params[:p6] -->
        
        <%= f.number_field :year , class: "form-control year", :value => params[:p7], placeholder: "Year" %> <!-- :value => params[:p7] -->
    </div>
    
    <%= f.label :birthdate, "Birthday" %>
    <%= f.date_field :birthdate, :start_year => 1900, class:'form-control date' %>
    
    <%= f.label :home_address, "Home Address" %>
    <%= f.text_area :home_address, :value => params[:p8], class: "form-control" %> <!-- :value => params[:p8] -->
    
    <h3>Contact Persons</h3><br/>
    <%= f.label "Father" %>
    <%= f.text_field :father, class: 'form-control', :value => params[:p10], placeholder: 'Full name'%>
    <%= f.label "Contact Number" %>
    <%= f.text_field :father_contact, class: 'form-control', :value => params[:p11], placeholder: 'Telephone / Cellphone number' %>
    <%= f.label "Occupation" %>
    <%= f.text_field :father_occupation, class: 'form-control', :value => params[:p12], placeholder: 'Occupation'%>
    
    <%= f.label "Mother" %>
    <%= f.text_field :mother, class: 'form-control', :value => params[:p13], placeholder: 'Full name'%>
    <%= f.label "Contact Number" %>
    <%= f.text_field :mother_contact, class: 'form-control', :value => params[:p14], placeholder: 'Telephone / Cellphone number' %>
    <%= f.label "Occupation" %>
    <%= f.text_field :mother_occupation, class: 'form-control', :value => params[:p15], placeholder: 'Occupation'%>
    
    <%= f.label "Guardian" %>
    <%= f.text_field :guardian, class: 'form-control', :value => params[:p16], placeholder: 'Full name'%>
    <%= f.label "Contact Number" %>
    <%= f.text_field :guardian_contact, class: 'form-control', :value => params[:p17], placeholder: 'Telephone / Cellphone number' %>
    <%= f.label "Occupation" %>
    <%= f.text_field :guardian_occupation, class: 'form-control', :value => params[:p18], placeholder: 'Occupation'%>
    
    <hr class = "invisible"/>
    
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    
    <hr class = "invisible"/>
    
<% end %>

app/views/ddms_users/_main_content.html.erb
<div class="mcontent">
    <%= render 'announcements' %>
    <hr/>
    <%= render 'rules' %>
    <hr/>
    <%= render 'personal_info' %>
</div>

app/views/ddms_users/_personal_info.html.erb
<div>
    <div class="personal-info">
        <h1>Personal Info</h1>
        <br/>
        <div class = "pad-left">
            <p>Room no: <%= @user.room_number %></p>
            <p>Name: <%= @user.last_name.capitalize %>, <%= @user.first_name.capitalize %> <%= @user.mi.capitalize %>.</p>
            <p>Student Number: <%= @user.student_no %></p>
            <p>Course & Year: <%= @user.course %> - <%= @user.year %></p>
            <% if @user.birthdate == nil %>
                <p>Birthday: </p>
                <p>Age: </p>
            <% else %>
                <p>Birthday: <%= @user.birthdate.strftime("%b. %d, %Y") %></p>
                <p>Age: <%= (Time.current.month.to_i - @user.birthdate.month >= 0 ? (Time.current.day.to_i - @user.birthdate.day >= 0 ? Time.current.year - @user.birthdate.strftime("%Y").to_i : Time.current.year - @user.birthdate.strftime("%Y").to_i - 1) : (Time.current.year - @user.birthdate.strftime("%Y").to_i - 1)) %></p>
            <% end %>
            <p>STS Bracket: <%= @user.sts_bracket %></p>
            <p>Home Address: <%= @user.home_address %></p>
            <p>Email: <%= @user.email %></p>
            <p>Contact: <%= @user.contact_no %></p>
            <br/>
            <h4>Contact Persons</h4>
            <p>Father's Name: <%= @user.father %></p>
            <p>Contact number: <%= @user.father_contact %></p>
            <p>Occuptation: <%= @user.father_occupation %></p><br/>
            <p>Mother's Name: <%= @user.mother %></p>
            <p>Contact number: <%= @user.mother_contact %></p>
            <p>Occupation: <%= @user.mother_occupation %></p><br/>
            
            <% if @user.guardian %>
                <p>Guardian: <%= @user.guardian %></p>
                <p>Contact number: <%= @user.guardian_contact %></p>
                <p>Occupation: <%= @user.guardian_occupation %></p><br/>
            <% end %>
        </div>
    </div>
    <hr/>
</div>

app/views/ddms_users/_side_bar.html.erb
<aside class = "sidetab card">
    <% if !current_user.admin? %>
    <div class="userinfo">
        <h3>
            <%= gravatar_for @user%>
            <%= @user.last_name %>, <%= @user.first_name %> <%= @user.mi%>.
        </h3>
        <%= @user.student_no %><br/>
        <%= @user.email %>
    </div>
    <hr/>
    <div class="options">
        <div class="users-btn">
            <div class= "btn side-opt"><span class="glyphicon glyphicon-bell"></span> <%= link_to "What's up? ", current_user %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-asterisk"></span> <%= link_to "Accountabilities ", url_for(current_user) + '/accountabilities' %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-thumbs-down"> </span><%= link_to " Violations ", url_for(current_user) + '/violations' %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-edit"></span> <%= link_to "Permits ", url_for(current_user) + '/permits' %></div>
        </div>
    </div>
    <div class='request'>
        <%= link_to "Request for a permit", ddms_permits_new_path(:user_id => current_user.id), class: 'btn btn-primary' %>
    </div>
    <% else %>
    <div class="options">
        <div class="admin-btn">
            <div class= "btn side-opt"><span class="glyphicon glyphicon-user"></span> <%= link_to "Manage Users ", ddms_users_path %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-edit"></span> <%= link_to "Manage Permits", ddms_permits_path %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-asterisk"> </span><%= link_to "Manage Accountabilities", ddms_accountabilities_path %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-thumbs-down"></span> <%= link_to "Manage Violations", ddms_violations_path %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-briefcase"></span> <%= link_to "Manage Applications", ddms_applicants_path %></div>
            <div class='btn side-opt'><span class="glyphicon glyphicon-bullhorn"></span> <%= link_to "Manage Announcements", ddms_announcements_path %></div>
        </div>    
    </div>
    
    <% end %>
</aside>

app/views/ddms_users/ddms_user_permits.html.erb
<div class="col-md-3 side">
    <%= render 'side_bar' %>
</div>
<div class = "user_bg col-md-9">
    <div class="title">
        <h1>Submitted Permits</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @permits.count > 0 %>
            <table class="table">
                <thead>
                    <tr>
                        <th>Permit type</th>
                        <th>Description</th>
                        <th>Permit Date</th>
                        <th>Date Created</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @permits.each do |permit| %>
                        <% if !permit.archived %>
                            <tr>
                                <!--<td>%= @users.find_by(:id => v.id).first_name %></td>-->
                                <td><%= permit.permit_type %></td>
                                <td><%= permit.description %></td>
                                <td><%= permit.permit_date.strftime("%d %b. %Y") %></td>
                                <td><%= permit.created_at.strftime("%d %b. %Y") %></td>
                                <td><%= (permit.approved ? 'Approved' : 'Unapproved') %></td>
                                <% if !permit.approved %>
                                    <td><%= link_to "Edit", edit_ddms_permit_path(:id => permit.id, :user_id => permit.user_id), class: 'btn btn-primary btn-sm' %></td>
                                <%else %>
                                    <td>---------</td>
                                <% end %>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            You have not submitted any permits. Click the button below to submit a permit request now.
            <div><%= link_to "Request Permit", ddms_permits_new_path(:user_id => current_user.id), class: 'btn btn-primary' %></div>
        <% end %>
    </div>
</div>

app/views/ddms_users/index.html.erb
<% provide(:title, "All Users") %>

<!--<div class="col-md-3 side">-->
<!--    %= render 'side_bar' %>-->
<!--</div>-->



<div class = "user_bg admin_view">
    <div>
        <%= link_to "Back", current_user, class: 'btn btn-primary' %>
        <%= link_to "Delete all archived data", delete_all_archived_ddms_user_path(current_user), class: 'btn btn-primary' %>
    </div>
    
    <div class="title">
        <h1>All Dormers</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @users.where(:archived => false, :admin => false).all.count > 0 %>
            <table class="table table-hover table-responsive">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Room Number</th>
                        <th>Student Number</th>
                        <th>Email</th>
                        <th>STS Bracket</th>
                        <th>Activation Status</th>
                        <th>Actions</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <% if !(user.admin?) && !user.archived? %>
                            <tr>
                                <td><%= user.id %></td>
                                <td><%= link_to "#{user.first_name}, #{user.last_name} #{user.mi}.", url_for(user) + '/personal-info' %></td>
                                <td><%= user.room_number %></td>
                                <td><%= user.student_no %></td>
                                <td><%= user.email %></td>
                                <td><%= user.sts_bracket %></td>
                                <td>
                                    <% if user.activated? %>
                                        Activated
                                    <% else %>
                                        Not Activated
                                    <% end %>
                                </td>
                                <td>
                                    <%= link_to "Edit", (user.activated ? edit_ddms_user_path(user) : '#'), class: 'btn btn-primary btn-sm' %>
                                    <%= link_to "Archive", change_ddms_user_path(user), data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-sm'%> 
                                    <%= link_to "Add Accountability", ddms_accountabilities_new_path(:user_id => user.id), class: 'btn btn-primary btn-sm' %>
                                    <%= link_to "Add Violation", ddms_violations_new_path(:user_id => user.id), class: 'btn btn-primary btn-sm' %>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No users
        <% end %>
    </div>
    <hr/>
    <div class="title">
        <h1>All Archived Dormers</h1>
    </div>
    <div class="showtable table-responsive">  <!-- dont forget na ig overflow hidden ini -->
        <% if @users.where(:archived => true, :admin => false).all.count > 0 %>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Student Number</th>
                        <th>Email</th>
                        <th>STS Bracket</th>
                        <th>Activation Status</th>
                        <th>Actions</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <% if !(user.admin?) && user.archived? %>
                            <tr>
                                <td><%= user.id %></td>
                                <td><%= user.first_name %></td>
                                <td><%= user.last_name %></td>
                                <td><%= user.student_no %></td>
                                <td><%= user.email %></td>
                                <td><%= user.sts_bracket %></td>
                                <td>
                                    <% if user.activated? %>
                                        Activated
                                    <% else %>
                                        Not Activated
                                    <% end %>
                                </td>
                                <td>
                                    <%= link_to "Restore", change_ddms_user_path(user), class: 'btn btn-primary btn-sm'%> 
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No archived users
        <% end %>
    </div>
</div>