config/routes.rb
Rails.application.routes.draw do

  get 'ddms_permits/edit'
  get 'ddms_permits/new'
  get 'ddms_permits/index'
  get 'ddms_accountabilities/new'
  get 'ddms_accountabilities/edit'
  get 'ddms_accountabilities/index'
  get 'ddms_violations/new'
  get 'ddms_violations/edit'
  get 'ddms_violations/index'
  get 'ddms_announcements/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'ddms_applicants/new'
  get 'ddms_users/new'

  root 'landing_page#home'
  
  resources :ddms_users
  resources :ddms_applicants
  resources :ddms_announcements
  resources :ddms_violations
  resources :ddms_accountabilities
  resources :ddms_permits
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: [:new, :edit, :create, :update]
  
  get 'landing_page/home'
  get 'landing_page/about'
  
  #================= routes for self defined methods ==================#
  
  get 'ddms_users/:id/violations',        to: 'ddms_users#ddms_user_violations'
  get 'ddms_users/:id/accountabilities',  to: 'ddms_users#ddms_user_accountabilities'
  get 'ddms_users/:id/permits',           to: 'ddms_users#ddms_user_permits'
  get 'ddms_users/:id/personal-info',     to: 'ddms_users#ddms_user_personal_info'
  
  get 'ddms_users/:id/all-announcements', to: 'ddms_users#all_announcements'
  # get 'ddms_users/:id/permits/new',       to: 'ddms_permits#new'
  
  #====================================================================#
  #====================================================================#
  
  #===================== TRY KO LA INI NA ROUTES ======================#
  resources :ddms_permits do
    member do
      get :approve
    end
  end
  resources :ddms_permits do
    member do
      get :archive
    end
  end
  resources :ddms_permits do
    member do
      get :delete_all_archived
    end
  end
  resources :ddms_accountabilities do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_accountabilities do
    member do
      get :resolve
    end
  end
  resources :ddms_violations do
    member do
      get :delete_resolved
    end
  end
  resources :ddms_violations do
    member do
      get :resolve
    end
  end
  resources :ddms_announcements do
    member do
      get :change
    end
  end
  
  resources :ddms_announcements do
    member do
      get :delete_archived
    end
  end
  
  resources :ddms_users do
    member do
      get :change
    end
  end
  
  resources :ddms_users do
    member do
      get :delete_all_archived
    end
  end
  
  #====================================================================#
  
  #=============================================
  
  # get '/apply', to: 'ddms_applicants#new'
  # get '/new', to: 'ddms_users#new'
  # post '/apply', to: 'ddms_applicants#create'
  # post '/new', to: 'ddms_users#create'
  get 'ddms_applicants/:id/change',   to: 'ddms_applicants#change'
  get 'ddms_users/deactivate',        to: 'ddms_users#deactivate'
  
  #==============================================
  
  #================ LOGIN IN LANDING PAGE SESSION ===============#
  
  get '/login',     to: 'landing_page#home'
  post '/login',    to: 'landing_page#create'
  delete '/logout', to: 'landing_page#destroy'
  
  #==============================================================#
  
  #=============== SESSION LOGIN ROUTES (WA GAMIT)=========================#
  
  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy'
  
  #==============================================================#
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ddms_announcement.rb
class DdmsAnnouncement < ApplicationRecord
    
    validates :title, presence: true, length: {maximum: 50}
    validates :content, presence: true, length: {maximum: 255}
    
end

app/controllers/ddms_announcements_controller.rb
class DdmsAnnouncementsController < ApplicationController
  
  before_action :admin_user, only: [:new, :index]
  
  def new
    @announcement = DdmsAnnouncement.new
  end
  
  def index
    @announcements = DdmsAnnouncement.all
  end
  
  def edit
    @announcement = DdmsAnnouncement.find(params[:id])
  end
  
  def update
    @announcement = DdmsAnnouncement.find(params[:id])
    if @announcement.update_attributes(announcement_params)
      flash[:success] = "Anouncement updated!"
      redirect_to ddms_announcements_path
    else
      render 'edit'
    end
  end
  
  def create
    @announcement = DdmsAnnouncement.create(announcement_params)
    if @announcement.save
      flash[:success] = "Announcement created."
      redirect_to ddms_announcements_path
    else
      render 'new'
    end
  end
  
  def destroy
    DdmsAnnouncement.find(params[:id]).destroy
    flash[:success] = "Announcement deleted."
    redirect_to ddms_announcements_path
  end
  
  #================ DELETES ARCHIVED ANNOUNCEMENTS (SELF DEFINED ROUTES LA INI) ====================#
  
  def change
    announcement = DdmsAnnouncement.find(params[:id])
    if !announcement.archived
      announcement.update_attribute(:archived, !announcement.archived)
    flash[:success] = "Announcement archived."
      redirect_to ddms_announcements_path
    else
      flash[:success] = "Announcement successfully restored. It will be removed from archived files."
      announcement.update_attribute(:archived, !announcement.archived)
      redirect_to ddms_announcements_path
    end
  end
  
  def delete_archived
    archived_announcements = DdmsAnnouncement.where(:archived => true).all
    if archived_announcements.count > 0
      if archived_announcements.destroy_all
        flash[:success] = "Deleted archived announcements."
        redirect_to ddms_announcements_path
      end
    else
      flash[:warning] = "No archived announcements at the moment."
      redirect_to ddms_announcements_path
    end
  end
  
  #==================================================================================================#
  
  private
  
    def admin_user
      unless admin_user? && logged_in?
        flash[:warning] = "You do not have administrative privileges."
        redirect_to root_url
      end
    end
    
    def announcement_params
      params.require(:ddms_announcement).permit(:title, :content)
    end
end

app/helpers/ddms_announcements_helper.rb
module DdmsAnnouncementsHelper
end

app/views/ddms_announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
    <!--render errors for this form-->
    <%= render 'shared/announcement_error_messages' %>
    
    <%= f.label :title%>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
    
    <%= f.label :content%>
    <%= f.text_area :content, class: 'form-control' %>
    
    <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
    
<% end %>

app/views/ddms_announcements/edit.html.erb
<% provide(:title, 'Edit announcement') %>
<% provide(:button_text, 'Save Changes') %>

<div class = "transparentbg">
    <!--<% if admin_user? %>
        <%= link_to "<< back", ddms_announcements_path %>
    <% end %>-->
    <div class = "formbg">
        <h1>Update Announcement</h1>
        <hr/>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <!--# % debugger %-->
                <%= render 'form' %>
                <hr class="invicible" />
                <%= link_to "Cancel", ddms_announcements_path, class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</div>

app/views/ddms_announcements/index.html.erb
<% provide(:title, "All Announcements") %>

<!--<div class="col-md-3 side">-->
<!--    <%= render 'ddms_users/side_bar' %>-->
<!--</div>-->
<div class = "user_bg admin_view">
    <div>
        <%= link_to "Back", current_user, class: 'btn btn-primary' %>
        <%= link_to "Create Announcement", ddms_announcements_new_path, class: 'btn btn-primary' %>
        <%= link_to "Delete All Archived Announcements", delete_archived_ddms_announcement_path(current_user),
            data: {confirm: "All archived announcements will be deleted. Are you sure?"}, class: 'btn btn-primary' %>
    </div>
    
    <div class="title">
        <h1>All Announcements</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @announcements.where(:archived => nil).all.count > 0 || @announcements.where(:archived => false).all.count > 0 %>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Author</th>
                        <th>Title</th>
                        <th>Content</th>
                        <th>Action</th> <!-- diretso na ini delete kay diri pwede bawi-un it approval -->
                    </tr>
                </thead>
                <tbody>
                    <% @announcements.each do |announcement| %>
                        <% if !announcement.archived %>
                            <tr>
                                <td>Administrator</td>
                                <td><%= announcement.title %></td>
                                <td><%= announcement.content %></td>
                                <td>
                                    <%= link_to "Edit", edit_ddms_announcement_path(announcement), class: 'btn btn-primary btn-sm' %>
                                    <%= link_to (announcement.archived ? "Restore" : "Archive") , change_ddms_announcement_path(announcement), class: 'btn btn-primary btn-sm'%>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No Posted Announcements
        <% end %>
    </div>
    
    <!-- ====================== ALL ARCHIVED ANNOUNCEMENTS ================================= -->
    
    <div class="title">
        <h1>Archived Announcements</h1>
    </div>
    <div class="showtable">  <!-- dont forget na ig overflow hidden ini -->
        <% if @announcements.where(:archived => true).all.count > 0 %>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Author</th>
                        <th>Title</th>
                        <th>Content</th>
                        <th>Action</th> <!-- diretso na ini delete kay diri pwede bawi-un it approval -->
                    </tr>
                </thead>
                <tbody>
                    <% @announcements.each do |announcement| %>
                        <% if announcement.archived %>
                            <tr>
                                <td>Administrator</td>
                                <td><%= announcement.title %></td>
                                <td><%= announcement.content %></td>
                                <td>
                                    <%= link_to (announcement.archived ? "Restore" : "Archive") , change_ddms_announcement_path(announcement), class: 'btn btn-primary btn-sm'%>
                                    <%= link_to "Delete" , announcement, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-sm'%>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% else %>
            No archived Announcements
        <% end %>
    </div>
</div>

app/views/ddms_announcements/new.html.erb
<%= provide(:title, "Create Announcement") %>
<%= provide(:button_text, "Post Announcement") %>

<div class = "transparentbg">
    <div class = "formbg">
        <h1>Announcement Form</h1>
        <hr/>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <!--# % debugger %-->
                <%= render 'form' %>
                <hr class="invicible" />
                <%= link_to "Cancel", ddms_announcements_path , class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</div>